version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  mongodb:
    build: .
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      mynetwork:
        aliases:
          - mongodb

  app:
    image: mongodb-mongodb
    environment:
      - MONGO_URI=mongodb://admin:adminpassword@mongodb:27017/grim-records
    depends_on:
      - mongodb
    networks:
      - mynetwork

volumes:
  mongo-data:
    driver: local
